### DISCUSSION TITLE
Support offline math render

### DISCUSSION THREAD

**Discussion by oovm** [notedge/panduck#3] [Ideas]
```toml
[dependencies.katex]
version = "0.4.2"
optional = true
default-features = false
features = ["duktape"]

[features]
default =["katex"]
```

```rs
pub fn katex(input: &str) -> Result<String> {
    let mut opts = katex::Opts::default();
    opts.set_output_type(OutputType::Html).build();
    opts.set_display_mode(true);
    katex::render_with_opts(input, &opts).map_err(|e| PanduckError::runtime_error(e))
}
```

http://pages.tzengyuxio.me/pandoc/#%E6%95%B8%E5%AD%B8
