### ISSUE TITLE
Support offline math render

### ISSUE THREAD

**Issue by oovm** [notedge/panduck#1]
```toml
[dependencies.katex]
version = "0.4.2"
optional = true
default-features = false
features = ["duktape"]

[features]
default =["katex"]
```
